spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doan?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: thai1201
    hikari:
      max-lifetime: 30000
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web: DEBUG
